name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Unit Tests
      run: dotnet test --verbosity normal tests/ValueWrapper.Tests.Unit
      env:
        CollectCoverage: true
        CoverletOutputFormat: opencover
        CoverletOutput: TestResults/
    - name: Integration Tests
      run: dotnet test --verbosity normal tests/ValueWrapper.Tests.Integration
      env:
        CollectCoverage: true
        CoverletOutputFormat: opencover
        CoverletOutput: TestResults/
    - name: Create Unit Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_unit_test_coverage_badge
      with:
        label: Unit Test Coverage
        color: brightgreen
        path: tests/ValueWrapper.Tests.Unit/TestResults/coverage.opencover.xml
        gist-filename: value-wrapper-unit-test-code-coverage.json
        gist-id: 529dfecfa3844f030a36d5ed38b82945
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}       
    - name: Print Unit Test Coverage
      run: echo "Code coverage percentage ${{steps.create_unit_test_coverage_badge.outputs.percentage}}%"
    - name: Print Unit Test Badge Data
      run: echo "Badge data ${{steps.create_unit_test_coverage_badge.outputs.badge}}"
    - name: Create Unit Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_integration_test_coverage_badge
      with:
        label: Integration Test Coverage
        color: brightgreen
        path: tests/ValueWrapper.Tests.Integration/TestResults/coverage.opencover.xml
        gist-filename: value-wrapper-integration-test-code-coverage.json
        gist-id: ddfe8cbe37e50e2484ecc87bbc79c9ac
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}
    - name: Print Integration Test Coverage
      run: echo "Code coverage percentage ${{steps.create_integration_test_coverage_badge.outputs.percentage}}%"
    - name: Print Integration Test Badge Data
      run: echo "Badge data ${{steps.create_integration_test_coverage_badge.outputs.badge}}"
    - name: Create NuGet package
      run: dotnet pack --no-build -c Release src/ValueWrapper/ValueWrapper.csproj -o .
    - name: Publish NuGet on version change
      run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate -n   
